---
- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
    update_cache: true
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  failed_when: false

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ tools_list | selectattr('apt', 'defined') | map(attribute='apt') | list }}"
    state: present
  become: true
