---
- name: Ensure bin_dir exists
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory
    mode: "0755"

- name: Download bare binary
  ansible.builtin.get_url:
    url: "{{ item.binary[platform_key].url }}"
    dest: "{{ bin_dir }}/{{ item.name }}-{{ item.binary.version }}"
    checksum: "{{ item.binary[platform_key].checksum }}"
    mode: "0755"
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - not item.binary[platform_key].archive | default(false)

- name: Download archive
  ansible.builtin.get_url:
    url: "{{ item.binary[platform_key].url }}"
    dest: "/tmp/{{ item.name }}-{{ item.binary.version }}.tar.gz"
    checksum: "{{ item.binary[platform_key].checksum }}"
    mode: "0644"
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - item.binary[platform_key].archive | default(false)
    - not (bin_dir + '/' + item.name + '-' + item.binary.version) is file

- name: Create extract directory
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}-{{ item.binary.version }}"
    state: directory
    mode: "0755"
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - item.binary[platform_key].archive | default(false)
    - not (bin_dir + '/' + item.name + '-' + item.binary.version) is file

- name: Extract archive
  ansible.builtin.unarchive:
    src: "/tmp/{{ item.name }}-{{ item.binary.version }}.tar.gz"
    dest: "/tmp/{{ item.name }}-{{ item.binary.version }}"
    remote_src: true
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - item.binary[platform_key].archive | default(false)
    - not (bin_dir + '/' + item.name + '-' + item.binary.version) is file

- name: Install binary from archive
  ansible.builtin.copy:
    src: "/tmp/{{ item.name }}-{{ item.binary.version }}/{{ item.binary[platform_key].archive_binary }}"
    dest: "{{ bin_dir }}/{{ item.name }}-{{ item.binary.version }}"
    mode: "0755"
    remote_src: true
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - item.binary[platform_key].archive | default(false)
    - not (bin_dir + '/' + item.name + '-' + item.binary.version) is file

- name: Remove archive
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}-{{ item.binary.version }}.tar.gz"
    state: absent
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - item.binary[platform_key].archive | default(false)
    - not (bin_dir + '/' + item.name + '-' + item.binary.version) is file

- name: Remove extract directory
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}-{{ item.binary.version }}"
    state: absent
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - platform_key in item.binary
    - item.binary[platform_key].archive | default(false)
    - not (bin_dir + '/' + item.name + '-' + item.binary.version) is file

- name: Symlink binary
  ansible.builtin.file:
    src: "{{ bin_dir }}/{{ item.name }}-{{ item.binary.version }}"
    dest: "{{ bin_dir }}/{{ item.name }}"
    state: link
    force: true
  loop: "{{ tools_list | selectattr('binary', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when: platform_key in item.binary
