repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: nix develop --command treefmt flake.nix nix/
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: statix
        name: statix
        entry: nix develop --command statix check --ignore 'vim/**' .
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: deadnix
        name: deadnix
        entry: nix develop --command deadnix --fail flake.nix nix/
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: nix-flake
        name: nix flake
        entry: nix flake check
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: just-fmt
        name: just --fmt
        entry: nix develop --command just --fmt --unstable
        language: system
        files: ^justfile$
        pass_filenames: false

      - id: shellcheck
        name: shellcheck
        entry: nix develop --command shellcheck
        language: system
        files: \.sh$

      - id: lua-format-check
        name: lua-language-server format check
        entry: nix develop --command lua-language-server --check .
        language: system
        files: \.lua$
        pass_filenames: false
