repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: treefmt flake.nix nix/
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: statix
        name: statix
        entry: statix check --ignore 'vim/**' .
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: deadnix
        name: deadnix
        entry: deadnix --fail flake.nix nix/
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: nix-flake
        name: nix flake
        entry: nix flake check
        language: system
        files: ^(flake\.nix|nix/)
        pass_filenames: false

      - id: just-fmt
        name: just --fmt
        entry: just --fmt --unstable
        language: system
        files: ^justfile$
        pass_filenames: false

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: \.sh$

      - id: stylua
        name: stylua
        entry: stylua
        language: system
        files: \.lua$
