---
- name: Install apt packages
  ansible.builtin.include_tasks: apt.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install snap packages
  ansible.builtin.include_tasks: snap.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install brew packages
  ansible.builtin.include_tasks: brew.yml
  when: ansible_facts['os_family'] == "Darwin"
