---
packages_apt:
  - ack
  - aptitude
  - geany
  - git
  - jq
  - photoflare
  - python3.13
  - python3.14
  - ripgrep
  - tmux
  - zsh

packages_snap:
  - name: nvim
    channel: latest/edge

packages_brew:
  - ack
  - fzf
  - git
  - jq
  - neovim
  - python@3.13
  - python@3.14
  - ripgrep
  - tmux
