---
- name: Ensure bin_dir exists
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory
    mode: "0755"

- name: Download bare binary
  ansible.builtin.get_url:
    url: "{{ item['url_' + platform_key] }}"
    dest: "{{ bin_dir }}/{{ item.name }}-{{ item.version }}"
    checksum: "{{ item['checksum_' + platform_key] }}"
    mode: "0755"
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - not (item.archive | default(false))

- name: Download archive
  ansible.builtin.get_url:
    url: "{{ item['url_' + platform_key] }}"
    dest: "/tmp/{{ item.name }}-{{ item.version }}.tar.gz"
    checksum: "{{ item['checksum_' + platform_key] }}"
    mode: "0644"
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - item.archive | default(false)

- name: Create extract directory
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}-{{ item.version }}"
    state: directory
    mode: "0755"
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - item.archive | default(false)

- name: Extract archive
  ansible.builtin.unarchive:
    src: "/tmp/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "/tmp/{{ item.name }}-{{ item.version }}"
    remote_src: true
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - item.archive | default(false)

- name: Install binary from archive
  ansible.builtin.copy:
    src: "/tmp/{{ item.name }}-{{ item.version }}/{{ item['archive_binary_' + platform_key] | default(item.archive_binary) }}"
    dest: "{{ bin_dir }}/{{ item.name }}-{{ item.version }}"
    mode: "0755"
    remote_src: true
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - item.archive | default(false)

- name: Remove archive
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}-{{ item.version }}.tar.gz"
    state: absent
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - item.archive | default(false)

- name: Remove extract directory
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}-{{ item.version }}"
    state: absent
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
    - item.archive | default(false)

- name: Symlink binary
  ansible.builtin.file:
    src: "{{ bin_dir }}/{{ item.name }}-{{ item.version }}"
    dest: "{{ bin_dir }}/{{ item.name }}"
    state: link
    force: true
  loop: "{{ binaries_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - (item.platforms is not defined) or (platform_key in item.platforms)
