---
- name: Check vim submodule update stamp
  ansible.builtin.stat:
    path: "{{ dotfiles_dir }}/.vim_submodule_updated"
  register: vim_submodule_stamp

- name: Update vim plugin submodules
  ansible.builtin.command: # noqa: command-instead-of-module
    cmd: git submodule update --init --remote vim/pack/plugins/start
    chdir: "{{ dotfiles_dir }}"
  register: vim_result
  changed_when: vim_result.stdout != ""
  when: not vim_submodule_stamp.stat.exists or
        vim_submodule_stamp.stat.mtime | int < (ansible_facts["date_time"]["epoch"] | int - 86400)

- name: Update vim submodule stamp
  ansible.builtin.file:
    path: "{{ dotfiles_dir }}/.vim_submodule_updated"
    state: touch
    mode: "600"
  when: vim_result is not skipped
  changed_when: false
