---
- name: Configure localhost
  hosts: localhost
  roles:
    - role: dotfiles
      tags: dotfiles
    - role: packages
      tags: packages
    - role: binaries
      tags: binaries
    - role: vim
      tags: vim
