---
name: lint

on:
  push:
  pull_request:

jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Format check
        run: nix develop ./nix --command treefmt --ci nix/

  statix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Lint (statix)
        run: nix develop ./nix --command statix check nix/

  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Dead code (deadnix)
        run: nix develop ./nix --command deadnix --fail nix/

  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check flake
        run: nix flake check ./nix

  just-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Format check
        run: just --fmt --check --unstable

  all-checks:
    if: ${{ !cancelled() }}
    needs:
      - nixfmt
      - statix
      - deadnix
      - flake-check
      - just-fmt
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - if: >-
          ${{ contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled') }}
        run: exit 1
