---
name: lint-all

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-all:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Run QA
        run: nix develop --command just lint
      - name: Run tests
        if: success() || failure()
        run: nix develop --command just test --with-junit
      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: 'reports/**/*.xml'
