---
name: lint-all

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
      - name: Run QA
        run: nix develop --command just lint-all
