---
name: test-all

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
      - name: Test 'bin/doc.pl'
        run: nix develop --command bats ./tests/doc.bats
      - name: Test 'deny-git-if-colocated.pl'
        run: nix develop --command bats ./claude/tests/hooks/deny-git-if-colocated.bats
